In [136]:
import pandas as pd
import numpy as np   # Needed to create NaN values

In [137]:
# Messy dataset - like real world data!
data = {
    'Employee':   ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Bob'],
    'Department': ['Data Science', ' ML Engineering', 'ML Engineering', 
                   'data science', None, 'Power BI'],
    'Salary':     [95000, 75000, None, 98000, 115000, 75000],
    'Experience': [4, 2, 6, None, 7, 2]
}
df = pd.DataFrame(data)
print("=== ORIGINAL MESSY DATA ====")
df

=== ORIGINAL MESSY DATA ====

  Employee       Department    Salary  Experience
0    Alice     Data Science   95000.0         4.0
1      Bob   ML Engineering   75000.0         2.0
2  Charlie   ML Engineering       NaN         6.0
3    Diana     data science   98000.0         NaN
4      Eve              NaN  115000.0         7.0
5      Bob         Power BI   75000.0         2.0

In [138]:
# --- STEP 1: Check missing values ---
print("=== MISSING VALUES ===")
df.isnull().sum()

=== MISSING VALUES ===

Employee      0
Department    1
Salary        1
Experience    1
dtype: int64

In [139]:
df.isnull().sum().sum() # total missing values in entire df

np.int64(3)

In [140]:
# --- STEP 2: Fill missing Salary with mean ---
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
print("=== After filling Salary with mean ===")
df['Salary']

=== After filling Salary with mean ===

0     95000.0
1     75000.0
2     91600.0
3     98000.0
4    115000.0
5     75000.0
Name: Salary, dtype: float64

In [141]:
df['Salary'].isnull().sum()

np.int64(0)

In [142]:
df[df['Department'].isnull()]

  Employee Department    Salary  Experience
4      Eve        NaN  115000.0         7.0

In [143]:
# --- STEP 3: Fill missing Department with 'Unknown' ---
df['Department'] = df['Department'].fillna('Unknown')

In [144]:
df['Department']

0       Data Science
1     ML Engineering
2     ML Engineering
3       data science
4            Unknown
5           Power BI
Name: Department, dtype: str

In [145]:
# --- STEP 4: Drop rows where Experience is missing ---
df.dropna(subset = ['Experience'], inplace = True)

In [146]:
# --- STEP 5: Fix Department — strip spaces & fix casing ---
df['Department'] = df['Department'].str.strip()
df['Department'] = df['Department'].str.title() # Title Case
print("=== After fixing Department ===")
df['Department']

=== After fixing Department ===

0      Data Science
1    Ml Engineering
2    Ml Engineering
4           Unknown
5          Power Bi
Name: Department, dtype: str

In [147]:
# --- STEP 6: Remove duplicate rows ---
print("\n=== Duplicates found:", df.duplicated().sum(), "===")
df.drop_duplicates(inplace=True)

=== Duplicates found: 0 ===

In [148]:
# --- STEP 7: Rename column ---
df.rename(columns={'Experience': 'Experience_Yrs'}, inplace=True)

In [149]:
# --- FINAL CLEAN DATA ---
print("=== FINAL CLEAN DATA ===")
df

=== FINAL CLEAN DATA ===

  Employee      Department    Salary  Experience_Yrs
0    Alice    Data Science   95000.0             4.0
1      Bob  Ml Engineering   75000.0             2.0
2  Charlie  Ml Engineering   91600.0             6.0
4      Eve         Unknown  115000.0             7.0
5      Bob        Power Bi   75000.0             2.0

In [150]:
print("Shape:", df.shape)

Shape: (5, 4)

In [151]:
print("Missing values left:", df.isnull().sum().sum())

Missing values left: 0

In [173]:
import pandas as pd
import numpy as np  # needed to create NaN values

# Messy dataset — like real world data!
data = {
    'Employee':   ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Bob'],
    'Department': ['Data Science', 'ML Engineering', 'ML Engineering', 
                   'data science', None, 'Power BI'],
    'Salary':     [95000, 75000, None, 98000, 115000, 75000],
    'Experience': [4, 2, 6, None, 7, 2]
}
df = pd.DataFrame(data)
print("=== ORIGINAL MESSY DATA ===")
print(df)

# --- STEP 1: Check missing values ---
print("\n=== MISSING VALUES ===")
print(df.isnull().sum())

# --- STEP 2: Fill missing Salary with mean ---
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
print("\n=== After filling Salary with mean ===")
print(df['Salary'])

# --- STEP 3: Fill missing Department with 'Unknown' ---
df['Department'] = df['Department'].fillna('Unknown')

# --- STEP 4: Drop rows where Experience is missing ---
df.dropna(subset=['Experience'], inplace=True)

# --- STEP 5: Fix Department — strip spaces & fix casing ---
df['Department'] = df['Department'].str.strip()
df['Department'] = df['Department'].str.title()  # Title Case
print("\n=== After fixing Department ===")
print(df['Department'])

# --- STEP 6: Remove duplicate rows ---
print("\n=== Duplicates found:", df.duplicated().sum(), "===")
df.drop_duplicates(inplace=True)

# --- STEP 7: Rename column ---
df.rename(columns={'Experience': 'Experience_Yrs'}, inplace=True)

# --- FINAL CLEAN DATA ---
print("\n=== FINAL CLEAN DATA ===")
print(df)
print("\nShape:", df.shape)
print("\nMissing values left:", df.isnull().sum().sum())

=== ORIGINAL MESSY DATA ===
  Employee      Department    Salary  Experience
0    Alice    Data Science   95000.0         4.0
1      Bob  ML Engineering   75000.0         2.0
2  Charlie  ML Engineering       NaN         6.0
3    Diana    data science   98000.0         NaN
4      Eve             NaN  115000.0         7.0
5      Bob        Power BI   75000.0         2.0

=== MISSING VALUES ===
Employee      0
Department    1
Salary        1
Experience    1
dtype: int64

=== After filling Salary with mean ===
0     95000.0
1     75000.0
2     91600.0
3     98000.0
4    115000.0
5     75000.0
Name: Salary, dtype: float64

=== After fixing Department ===
0      Data Science
1    Ml Engineering
2    Ml Engineering
4           Unknown
5          Power Bi
Name: Department, dtype: str

=== Duplicates found: 0 ===

=== FINAL CLEAN DATA ===
  Employee      Department    Salary  Experience_Yrs
0    Alice    Data Science   95000.0             4.0
1      Bob  Ml Engineering   75000.0             2.0
2  Charlie  Ml Engineering   91600.0             6.0
4      Eve         Unknown  115000.0             7.0
5      Bob        Power Bi   75000.0             2.0

Shape: (5, 4)

Missing values left: 0

In [153]:

# --- STEP 6: Remove duplicate rows ---
print("\n=== Duplicates found:", df.duplicated().sum(), "===")
df.drop_duplicates(inplace=True)

# --- STEP 7: Rename column ---
df.rename(columns={'Experience': 'Experience_Yrs'}, inplace=True)

# --- FINAL CLEAN DATA ---
print("\n=== FINAL CLEAN DATA ===")
print(df)
print("\nShape:", df.shape)
print("\nMissing values left:", df.isnull().sum().sum())

=== Duplicates found: 0 ===

=== FINAL CLEAN DATA ===
  Employee      Department    Salary  Experience_Yrs
0    Alice    Data Science   95000.0             4.0
1      Bob  Ml Engineering   75000.0             2.0
2  Charlie  Ml Engineering   91600.0             6.0
4      Eve         Unknown  115000.0             7.0
5      Bob        Power Bi   75000.0             2.0

Shape: (5, 4)

Missing values left: 0

dropna remove empty right, so NaN,  '', 0, False, empty values, and i migth miss any other to tell and these comes under empty and does dropna will remove all these? does this function work like that?

In [156]:
data = {
    'Product':  ['Humira', 'skyrizi', ' Rinvoq', 'Botox', 'Humira', None],
    'Category': ['Immunology', 'Immunology', None, 'Neuroscience', 
                 'Immunology', 'Neuroscience'],
    'Revenue':  [14.3, 4.1, 2.8, None, 14.3, 1.9],
    'Year':     [2023, 2023, 2023, 2023, 2023, 2023]
}

In [157]:
df = pd.DataFrame(data)
df

   Product      Category  Revenue  Year
0   Humira    Immunology     14.3  2023
1  skyrizi    Immunology      4.1  2023
2   Rinvoq           NaN      2.8  2023
3    Botox  Neuroscience      NaN  2023
4   Humira    Immunology     14.3  2023
5      NaN  Neuroscience      1.9  2023

In [158]:
# 1. Check how many missing values exist in each column
df.isnull().sum()

Product     1
Category    1
Revenue     1
Year        0
dtype: int64

In [159]:
# 2. Fill missing Revenue with the median (not mean this time!)
df['Revenue'].fillna(df['Revenue'].median(), inplace=True)

C:\Users\THATTSR\AppData\Local\Temp\ipykernel_16136\2947546330.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Revenue'].fillna(df['Revenue'].median(), inplace=True)

0    14.3
1     4.1
2     2.8
3     4.1
4    14.3
5     1.9
Name: Revenue, dtype: float64

In [160]:
# 3. 
df['Revenue'] =df['Revenue'].fillna(df['Revenue'].median())

In [161]:
df['Revenue']

0    14.3
1     4.1
2     2.8
3     4.1
4    14.3
5     1.9
Name: Revenue, dtype: float64

In [162]:
# 3. Fill missing Category with 'Other'
df['Category'] = df['Category'].fillna('Other')
df['Category']

0      Immunology
1      Immunology
2           Other
3    Neuroscience
4      Immunology
5    Neuroscience
Name: Category, dtype: str

In [163]:
df['Product']

0     Humira
1    skyrizi
2     Rinvoq
3      Botox
4     Humira
5        NaN
Name: Product, dtype: str

In [164]:
# 4. Drop rows where Product is missing
df.dropna(subset={'Product'}, inplace=True)
df['Product']

0     Humira
1    skyrizi
2     Rinvoq
3      Botox
4     Humira
Name: Product, dtype: str

In [165]:
# 5. Fix Product column — strip spaces and apply title case
df['Product']= df['Product'].str.strip()
df['Product']= df['Product'].str.title()

In [166]:
# 6. Remove duplicate rows
df.drop_duplicates(inplace=True)

In [167]:
df

   Product      Category  Revenue  Year
0   Humira    Immunology     14.3  2023
1  Skyrizi    Immunology      4.1  2023
2   Rinvoq         Other      2.8  2023
3    Botox  Neuroscience      4.1  2023

In [168]:
# 7. Rename Revenue column to Revenue_B
df.rename(columns={'Revenue':'Revenue_B'}, inplace=True)

In [169]:
df

   Product      Category  Revenue_B  Year
0   Humira    Immunology       14.3  2023
1  Skyrizi    Immunology        4.1  2023
2   Rinvoq         Other        2.8  2023
3    Botox  Neuroscience        4.1  2023

In [170]:
# 8. Print final clean DataFrame and confirm 0 missing values
df.shape

(4, 4)

In [171]:
df

   Product      Category  Revenue_B  Year
0   Humira    Immunology       14.3  2023
1  Skyrizi    Immunology        4.1  2023
2   Rinvoq         Other        2.8  2023
3    Botox  Neuroscience        4.1  2023

In [172]:
df.isnull().sum().sum()

np.int64(0)