In [1]:
import pandas as pd

In [18]:
data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Department': ['Data Science', 'Power BI', 'ML Engineering',
                   'Data Science', 'ML Engineering'],
    'Salary': [95000, 75000, 110000, 98000, 115000],
    'Experience_Yrs': [4, 2, 6, 5, 7]
}
df = pd.DataFrame(data)
df

  Employee      Department  Salary  Experience_Yrs
0    Alice    Data Science   95000               4
1      Bob        Power BI   75000               2
2  Charlie  ML Engineering  110000               6
3    Diana    Data Science   98000               5
4      Eve  ML Engineering  115000               7

In [3]:
# -- Column Selection ---
print("=== Singel Column (Series) ===")
df['Salary']

=== Singel Column (Series) ===

0     95000
1     75000
2    110000
3     98000
4    115000
Name: Salary, dtype: int64

In [4]:
print("==== Multiple Columns (DataFrame) ===")
df[['Employee', 'Department']]

==== Multiple Columns (DataFrame) ===

  Employee      Department
0    Alice    Data Science
1      Bob        Power BI
2  Charlie  ML Engineering
3    Diana    Data Science
4      Eve  ML Engineering

In [5]:
# --- Row Filtering ---
print("=== Salary > 100000 ====")
df[df['Salary']>100000]

=== Salary > 100000 ====

  Employee      Department  Salary  Experience_Yrs
2  Charlie  ML Engineering  110000               6
4      Eve  ML Engineering  115000               7

In [6]:
print("=== Data Science AND Experience > 3 ===")
df[(df['Department'] == 'Data Science') & (df['Experience_Yrs']>3)]

=== Data Science AND Experience > 3 ===

  Employee    Department  Salary  Experience_Yrs
0    Alice  Data Science   95000               4
3    Diana  Data Science   98000               5

In [10]:
print("=== NOT Pwer BI ===")
df[~(df['Department'] == 'Power BI')]

=== NOT Pwer BI ===

  Employee      Department  Salary  Experience_Yrs
0    Alice    Data Science   95000               4
2  Charlie  ML Engineering  110000               6
3    Diana    Data Science   98000               5
4      Eve  ML Engineering  115000               7

In [16]:
# -- loc & iloc ---
print("=== loc: rows 0-2, Employee & Salary ===")
df.loc[0:2, ['Employee', 'Salary']]

=== loc: rows 0-2, Employee & Salary ===

  Employee  Salary
0    Alice   95000
1      Bob   75000
2  Charlie  110000

In [20]:
print("=== iloc: first 3 rows, first 2 columns ===")
df.iloc[0:3, [0, 1]]

=== iloc: first 3 rows, first 2 columns ===

  Employee      Department
0    Alice    Data Science
1      Bob        Power BI
2  Charlie  ML Engineering

In [ ]:
# Exercise
# 1. Select only the Department and Experience_Yrs columns
df[['Department', 'Experience_Yrs']]

       Department  Experience_Yrs
0    Data Science               4
1        Power BI               2
2  ML Engineering               6
3    Data Science               5
4  ML Engineering               7

In [ ]:
# 2. Filter employees whose Experience is more than 4 years
df[df['Experience_Yrs']>4]

  Employee      Department  Salary  Experience_Yrs
2  Charlie  ML Engineering  110000               6
3    Diana    Data Science   98000               5
4      Eve  ML Engineering  115000               7

In [33]:
# 3 .Filter employees who are in ML Engineering AND salary > 110000
df[(df['Department'] == 'ML Engineering') & (df['Salary']>110000)]

  Employee      Department  Salary  Experience_Yrs
4      Eve  ML Engineering  115000               7

In [34]:
# 4. Filter employees who are in Data Science OR have salary < 80000
df[(df['Department']=='Data Science') | (df['Salary']< 80000)]

  Employee    Department  Salary  Experience_Yrs
0    Alice  Data Science   95000               4
1      Bob      Power BI   75000               2
3    Diana  Data Science   98000               5

In [35]:
# 5. Using loc → get rows 1 to 3 and columns Employee, Salary, Experience_Yrs
df.loc[1:3, ['Employee', 'Salary', 'Experience_Yrs']]

  Employee  Salary  Experience_Yrs
1      Bob   75000               2
2  Charlie  110000               6
3    Diana   98000               5

In [ ]:
# 6. Using iloc → get the last 2 rows and last 2 columns
df.iloc[-2:, -2:]

   Salary  Experience_Yrs
3   98000               5
4  115000               7

In [39]:
df.loc[1:3]    # rows 1, 2, 3  ← end IS included

  Employee      Department  Salary  Experience_Yrs
1      Bob        Power BI   75000               2
2  Charlie  ML Engineering  110000               6
3    Diana    Data Science   98000               5

In [40]:
df.iloc[1:3]   # rows 1, 2     ← end is NOT included

  Employee      Department  Salary  Experience_Yrs
1      Bob        Power BI   75000               2
2  Charlie  ML Engineering  110000               6