<h3>Pandas Cheat Sheet – Core Commands</h3><table><tr><th>Concept</th><th>What It Does</th></tr><tr><td><code>pd.DataFrame()</code></td><td>Create a table</td></tr><tr><td><code>df.head()</code></td><td>See first 5 rows</td></tr><tr><td><code>df.info()</code></td><td>Check data types</td></tr><tr><td><code>df.describe()</code></td><td>Summary statistics</td></tr><tr><td><code>df.loc[]</code> / <code>df.iloc[]</code></td><td>Select rows/columns</td></tr><tr><td><code>df.dropna()</code></td><td>Remove missing values</td></tr><tr><td><code>df.groupby()</code></td><td>Group & aggregate (like Power BI grouping)</td></tr><tr><td><code>df.merge()</code></td><td>Join tables (like SQL JOIN)</td></tr><tr><td><code>df.apply()</code></td><td>Apply a function to a column</td></tr></table>

In [1]:
# Step 1 - Import pandas
import pandas as pd

In [6]:
# Step 2 - Create a DataFrame
data = {
    'Drug': ['Humira', 'Skyrizi', 'Rinvoq', 'Botox', 'Vraylar'],
    'Revenue_B': [14.3, 4.1, 2.8, 2.6, 1.9],
    'Year': [2023, 2023, 2023, 2023, 2023],
    'Therapy_Area':['Immunology','Immunology','Immunology','Neuroscience','Neuroscience']
}

df = pd.DataFrame(data)
df

      Drug  Revenue_B  Year  Therapy_Area
0   Humira       14.3  2023    Immunology
1  Skyrizi        4.1  2023    Immunology
2   Rinvoq        2.8  2023    Immunology
3    Botox        2.6  2023  Neuroscience
4  Vraylar        1.9  2023  Neuroscience

In [4]:
# Step 3 - Explore it
print("=== HEAD ===")
df.head()

=== HEAD ===

      Drug  Revenue_B  Year  Therapy_Area
0   Humira       14.3  2023    Immunology
1  Skyrizi        4.1  2023    Immunology
2   Rinvoq        2.8  2023    Immunology
3    Botox        2.6  2023  Neuroscience
4  Vraylar        1.9  2023  Neuroscience

In [7]:
print("=== SHAPE ===")
df.shape

=== SHAPE ===

(5, 4)

In [11]:
print("=== INFO ===")
df.info()

=== INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Drug          5 non-null      str
 1   Revenue_B     5 non-null      float64
 2   Year          5 non-null      int64
 3   Therapy_Area  5 non-null      str
dtypes: float64(1), int64(1), str(2)
memory usage: 292.0 bytes

In [12]:
print("=== DESCRIBE ===")
df.describe()

=== DESCRIBE ===

       Revenue_B    Year
count   5.000000     5.0
mean    5.140000  2023.0
std     5.181988     0.0
min     1.900000  2023.0
25%     2.600000  2023.0
50%     2.800000  2023.0
75%     4.100000  2023.0
max    14.300000  2023.0

In [16]:
# Exercise 1
employee_data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Department': ['Data Science', 'Power BI', 'ML Engineering', 'Data Science', 'ML Engineering'],
    'Salary': [95000, 75000, 110000, 98000, 115000],
    'Experience_Yrs': [4, 2, 6, 5, 7]
}
employee_data = pd.DataFrame(employee_data)
employee_data

  Employee      Department  Salary  Experience_Yrs
0    Alice    Data Science   95000               4
1      Bob        Power BI   75000               2
2  Charlie  ML Engineering  110000               6
3    Diana    Data Science   98000               5
4      Eve  ML Engineering  115000               7

In [ ]:
# 1. Print the first 3 rows using head()
employee_data.head(3)

  Employee      Department  Salary  Experience_Yrs
0    Alice    Data Science   95000               4
1      Bob        Power BI   75000               2
2  Charlie  ML Engineering  110000               6

In [ ]:
# 2. How many rows and columns does it have?
employee_data.shape

(5, 4)

In [ ]:
# 3. What are the data types of each column?
employee_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Employee        5 non-null      str
 1   Department      5 non-null      str
 2   Salary          5 non-null      int64
 3   Experience_Yrs  5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [ ]:
# 4. What is the average salary and max experience? (use describe())
employee_data.describe()

              Salary  Experience_Yrs
count       5.000000        5.000000
mean    98600.000000        4.800000
std     15565.988565        1.923538
min     75000.000000        2.000000
25%     95000.000000        4.000000
50%     98000.000000        5.000000
75%    110000.000000        6.000000
max    115000.000000        7.000000

In [21]:
df.shape

(5, 4)

In [22]:
df.dtypes

Drug                str
Revenue_B       float64
Year              int64
Therapy_Area        str
dtype: object

In [ ]:
df.columns

Index(['Drug', 'Revenue_B', 'Year', 'Therapy_Area'], dtype='str')

In [24]:
df.size

20